name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: List current directory
      run: |
        dir
        
    - name: Create folders if they don't exist
      run: |
        if (-not (Test-Path "static")) { New-Item -ItemType Directory -Path "static" }
        if (-not (Test-Path "templates")) { New-Item -ItemType Directory -Path "templates" }
        
    - name: List directories after creation
      run: |
        dir
        echo "Contents of templates directory:"
        if (Test-Path "templates") { dir templates }
        echo "Contents of static directory:"
        if (Test-Path "static") { dir static }
        
    - name: Verify Python environment
      run: |
        python --version
        pip list
        
    - name: Verify werkzeug installation
      run: |
        python -c "import werkzeug; print('Werkzeug version:', werkzeug.__version__)"
        python -c "from werkzeug.urls import url_quote; print('url_quote available')"
        
    - name: Build executable
      run: |
        pyinstaller --onefile ^
          --add-data "templates;templates" ^
          --add-data "static;static" ^
          --collect-all werkzeug ^
          --collect-all flask ^
          --collect-all jinja2 ^
          --collect-all flask_cors ^
          --collect-all click ^
          --hidden-import werkzeug.urls ^
          --hidden-import werkzeug.utils ^
          --hidden-import werkzeug.routing ^
          --hidden-import werkzeug.datastructures ^
          --hidden-import werkzeug.middleware ^
          --hidden-import werkzeug.middleware.proxy_fix ^
          --hidden-import flask ^
          --hidden-import flask.cli ^
          --hidden-import flask.helpers ^
          --hidden-import flask_cors ^
          --hidden-import jinja2 ^
          --hidden-import jinja2.ext ^
          --name CourtScraper run.py
          
    - name: List dist directory
      run: |
        echo "Contents of dist directory:"
        dir dist
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CourtScraper
        path: dist/CourtScraper.exe
        retention-days: 5

    - name: Verify executable exists
      run: |
        if (Test-Path "dist/CourtScraper.exe") {
          echo "Executable created successfully"
          Get-Item "dist/CourtScraper.exe" | Select-Object Length
        } else {
          echo "Error: Executable not found"
          exit 1
        }

    - name: Check executable permissions
      run: |
        $acl = Get-Acl "dist/CourtScraper.exe"
        echo "File permissions:"
        $acl.Access | Format-Table IdentityReference,FileSystemRights,AccessControlType -AutoSize
